apiVersion: v1
kind: Secret
metadata:
  name: opsgenie-shift-reporter
  namespace: opsgenie-shift-reporter
type: Opaque
data:
  opsgenie-key: {{ .Values.opsgenie.key }}
  slack-key: {{ .Values.slack.key }}
