apiVersion: v1
kind: Secret
metadata:
  name: opsgenie-shift-reporter
  namespace: opsgenie-shift-reporter
type: Opaque
data:
  OPSGENIE_KEY: {{ .Values.opsgenie.key }}
  SLACK_KEY: {{ .Values.slack.key }}
