apiVersion: batch/v1
kind: CronJob
metadata:
  name: opsgenie-shift-reporter
  namespace: opsgenie-shift-reporter
spec:
  schedule: "0 6 20 * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
          containers:
          - name: opsgenie-shift-reporter
            image: quay.io/giantswarm/opsgenie-shift-reporter:latest
            imagePullPolicy: Always
            args:
            - -opsgenie-key=$(opsgenie-key)
            - -slack-key=$(slack-key)
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              seccompProfile:
                type: RuntimeDefault
            env:
            - name: opsgenie-key
              valueFrom:
                secretKeyRef:
                  name: opsgenie-shift-reporter
                  key: opsgenie-key
            - name: slack-key
              valueFrom:
                secretKeyRef:
                  name: opsgenie-shift-reporter
                  key: slack-key
          restartPolicy: Never
